# Generated by Django 4.2.3 on 2023-10-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Customer Profile'},
        ),
    ]
