# Generated by Django 4.2.3 on 2023-10-03 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('NID', 'NID'), ('Passport', 'Passport'), ('Driving Licence', 'Driving Licence')], default='NID', max_length=20)),
                ('first_and_last_name', models.CharField(max_length=25)),
                ('Nid_number', models.CharField(max_length=20)),
                ('NID_copy_1', models.FileField(upload_to='')),
                ('NID_copy_2', models.FileField(upload_to='')),
                ('shop_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('upazila', models.CharField(max_length=20)),
                ('warehouse_address', models.BooleanField(default=True)),
                ('w_address', models.CharField(blank=True, max_length=300, null=True)),
                ('w_division', models.CharField(blank=True, max_length=20, null=True)),
                ('w_district', models.CharField(blank=True, max_length=20, null=True)),
                ('w_upazila', models.CharField(blank=True, max_length=20, null=True)),
                ('return_address', models.BooleanField(default=True)),
                ('r_address', models.CharField(blank=True, max_length=300, null=True)),
                ('r_division', models.CharField(blank=True, max_length=20, null=True)),
                ('r_district', models.CharField(blank=True, max_length=20, null=True)),
                ('r_upazila', models.CharField(blank=True, max_length=20, null=True)),
                ('account_title', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_branch_name', models.CharField(max_length=30)),
                ('routing_number', models.CharField(max_length=30)),
                ('cheque_copy', models.FileField(upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendor Profile',
            },
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='other_vendors.district')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='other_vendors.country')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='other_vendors.division'),
        ),
    ]
