# Generated by Django 4.2.3 on 2023-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_vendors', '0004_alter_vendorinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinformation',
            name='vendor_image',
            field=models.ImageField(blank=True, default='no_img.png', null=True, upload_to='vendor_image/'),
        ),
    ]
